# Generated by Django 5.2.7 on 2025-10-22 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('total_orders', models.PositiveIntegerField(default=0, verbose_name='عدد الطلبات')),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='إجمالي المبيعات')),
            ],
            options={
                'verbose_name': 'تقرير يومي',
                'verbose_name_plural': 'التقارير اليومية',
                'ordering': ['-date'],
            },
        ),
    ]
