# Generated by Django 5.2.7 on 2025-10-22 10:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyreport',
            options={'ordering': ['-report_date'], 'verbose_name': 'تقرير يومي', 'verbose_name_plural': 'التقارير اليومية'},
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='date',
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='report_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ التقرير'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='total_orders',
            field=models.PositiveIntegerField(verbose_name='عدد الطلبات'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='total_sales',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='إجمالي المبيعات'),
        ),
    ]
